[package]
name = "wasm_examples_gol"
version = "0.1.0"
authors = ["zaixrx <kouamohamedanis@gmail.com>"]
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.101"
wasm-bindgen-test = "0.3.51"
rand= "0.9.2"
